CREATE TABLE TESTUSER01.USERS
(
    NAME    VARCHAR2(50) PRIMARY KEY,
    GENDER      VARCHAR2(1)
);

ALTER TABLE TESTUSER01.USERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO TESTUSER01.USERS (NAME, GENDER)
VALUES ('Dominik', 'M'),
('David', 'M');
