version: "3.2"
services:
  # for development purposes
  dev:
    build:
      context: ../../
      dockerfile: db_components/ex_postgres_cdc/Dockerfile
    volumes:
      - ./:/code/db_components/ex_postgres_cdc/
      - ./data:/data
    environment:
      - KBC_DATADIR=/data
  test:
    # Use to run flake8 and unittests checks
    build:
      context: ../../
      dockerfile: db_components/ex_postgres_cdc/Dockerfile
    volumes:
      - ./:/code/db_components/ex_postgres_cdc/
      - ./data:/data
    environment:
      - KBC_DATADIR=/data
    command:
      - /bin/sh
      - /code/scripts/build_n_test.sh