services:
  # for development purposes
  dev: &app
    links:
      - postgres
    build:
      context: ../../
      dockerfile: db_components/ex_postgres_cdc/Dockerfile
    volumes:
      - ./:/code/db_components/ex_postgres_cdc/
      - ./data:/data
    environment:
      - KBC_DATADIR=/data
  postgres:
    image: debezium/example-postgres:2.5.1.Final
    environment:
      DK_JAVA_OPTIONS: -Xmx1600m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/dumps
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
  wait:
    image: waisbrot/wait
    depends_on:
      - postgres
    environment:
      - TARGETS=postgres:5432
      - TIMEOUT=200
  tests:
    # Use to run flake8 and unittests checks
    <<: *app
    links:
      - postgres
    volumes:
      - ./:/code/db_components/ex_postgres_cdc/
    environment:
      PGSQL_HOST: ${PGSQL_HOST}
      PGSQL_USER: ${PGSQL_USER}
      PGSQL_PASSWORD: ${PGSQL_PASSWORD}
      PGSQL_DATABASE: ${PGSQL_DATABASE}
      PGSQL_PORT: ${PGSQL_PORT}
    command:
      - /bin/sh
      - -c
      - |
        set -e
        cd /code/db_components/ex_postgres_cdc
        python -m unittest discover