on:
  workflow_call:
    inputs:
      APP_NAME: # Controls the path to source code
        required: true
        type: string
      APP_ID: # The app ID to deploy
        required: true
        type: string
      KBC_DEVELOPERPORTAL_VENDOR:
        required: true
        type: string
      KBC_DEVELOPERPORTAL_USERNAME:
        required: true
        type: string
      DOCKERHUB_USER:
        required: true
        type: string
      TAG:
        required: true
        type: string
      IS_SEMANTIC_TAG:
        required: true
        type: string

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download JAR Artifact
      uses: actions/download-artifact@v4
      with:
        name: java-artifact

    - name: Move JAR Artifact
      run: mv kbcDebeziumEngine-jar-with-dependencies.jar debezium_core/jars/kbcDebeziumEngine-jar-with-dependencies.jar

    - name: Docker login
      run: docker login --username "${{ inputs.DOCKERHUB_USER }}" --password "${{ secrets.DOCKERHUB_TOKEN }}"

    - name: Set APP_PATH variable
      run: echo "APP_PATH=$(echo ${{ inputs.APP_NAME }} | tr '-' '_')" >> $GITHUB_ENV

    - name: Build image
      run: docker build -t ${{ inputs.APP_NAME }} -f db_components/${{ env.APP_PATH }}/Dockerfile .

    - name: Push image to ECR
      uses: keboola/action-push-to-ecr@master
      with:
        vendor: ${{ inputs.KBC_DEVELOPERPORTAL_VENDOR }}
        app_id: ${{ inputs.KBC_DEVELOPERPORTAL_VENDOR }}.${{ inputs.APP_ID }}
        username: ${{ inputs.KBC_DEVELOPERPORTAL_USERNAME }}
        password: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
        tag: ${{ inputs.TAG }}
        push_latest: ${{ inputs.IS_SEMANTIC_TAG }}
        source_image: ${{ inputs.APP_NAME }}