on:
  workflow_call:
    inputs:
      VENDOR:
        required: true
        type: string
      APP_ID:
        required: true
        type: string
      USERNAME:
        required: true
        type: string
      TAG:
        required: false
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag in the Developer Portal
        uses: keboola/action-set-tag-developer-portal@master
        with:
          vendor: ${{ inputs.VENDOR }}
          app_id: ${{ inputs.APP_ID }}
          username: ${{ inputs.USERNAME }}
          password: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ inputs.TAG }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set App Environment Variables
        run: |
          echo "KBC_COMPONENT=${{ inputs.APP_ID }}" >> KBC_COMPONENT
          echo "KBC_DEVELOPERPORTAL_USERNAME=${{ inputs.USERNAME }}" >> KBC_DEVELOPERPORTAL_USERNAME
          echo "KBC_DEVELOPERPORTAL_VENDOR=${{ inputs.VENDOR }}" >> KBC_DEVELOPERPORTAL_VENDOR

      - name: Set developer portal properties
        run: |
            chmod +x scripts/update_dev_portal_properties.sh
            scripts/update_dev_portal_properties.sh
