on:
  workflow_call:
    inputs:
      VENDOR:
        required: true
        type: string
      APP_ID:
        required: true
        type: string
      USERNAME:
        required: true
        type: string
      TAG:
        required: false
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && needs.build-python.outputs.is_semantic_tag == 'true'
    steps:
      - name: Set tag in the Developer Portal
        uses: keboola/action-set-tag-developer-portal@master
        with:
          vendor: ${{ inputs.VENDOR }}
          app_id: ${{ inputs.APP_ID }}
          username: ${{ inputs.USERNAME }}
          password: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ inputs.TAG }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set App ID as Environment Variable
        run: echo "KBC_COMPONENT=${{ inputs.APP_ID }}" >> $GITHUB_ENV

      - name: Set developer portal properties
        run: |
            chmod +x scripts/update_dev_portal_properties.sh
            scripts/update_dev_portal_properties.sh
