on:
  workflow_call:
    inputs:
      VENDOR:
        required: true
        type: string
      APP_ID:
        required: true
        type: string
      USERNAME:
        required: true
        type: string
      TAG:
        required: false
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        KBC_COMPONENT: ${{ inputs.APP_ID }}
        KBC_DEVELOPERPORTAL_USERNAME: ${{ inputs.USERNAME }}
        KBC_DEVELOPERPORTAL_VENDOR: ${{ inputs.VENDOR }}
        KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
    steps:
      - name: Set tag in the Developer Portal
        uses: keboola/action-set-tag-developer-portal@master
        with:
          vendor: ${{ inputs.VENDOR }}
          app_id: ${{ inputs.APP_ID }}
          username: ${{ inputs.USERNAME }}
          password: ${{ env.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ inputs.TAG }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update developer portal properties
        run: |
          chmod +x scripts/update_dev_portal_properties.sh
          scripts/update_dev_portal_properties.sh