name: ex-postgres-cdc Build & Deploy
on: [ push ]
concurrency: ci-${{ github.ref }} # to avoid tag collisions in the ECR
env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  APP_NAME1: "ex-postgres-cdc"
  APP_NAME2: "ex-postgres-cdc-duck"
  KBC_DEVELOPERPORTAL_VENDOR: "kds-team"
  KBC_DEVELOPERPORTAL_USERNAME: "kds-team+github"
  KBC_TEST_PROJECT_CONFIGS: "995161343" # space separated list of config ids
  DOCKERHUB_USER: "keboolabot"
  PGSQL_HOST: postgres
  PGSQL_USER: postgres
  PGSQL_PASSWORD: postgres
  PGSQL_DATABASE: postgres
  PGSQL_PORT: 5432

jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      APP_NAME1: ${{ steps.step1.outputs.APP_NAME1 }}
      APP_NAME2: ${{ steps.step1.outputs.APP_NAME2 }}
      KBC_DEVELOPERPORTAL_VENDOR: ${{ steps.step1.outputs.KBC_DEVELOPERPORTAL_VENDOR }}
      KBC_DEVELOPERPORTAL_USERNAME: ${{ steps.step1.outputs.KBC_DEVELOPERPORTAL_USERNAME }}
      KBC_TEST_PROJECT_CONFIGS: ${{ steps.step1.outputs.KBC_TEST_PROJECT_CONFIGS }}
      DOCKERHUB_USER: ${{ steps.step1.outputs.DOCKERHUB_USER }}
      PGSQL_HOST: ${{ steps.step1.outputs.PGSQL_HOST }}
      PGSQL_USER: ${{ steps.step1.outputs.PGSQL_USER }}
      PGSQL_PASSWORD: ${{ steps.step1.outputs.PGSQL_PASSWORD }}
      PGSQL_DATABASE: ${{ steps.step1.outputs.PGSQL_DATABASE }}
      PGSQL_PORT: ${{ steps.step1.outputs.PGSQL_PORT }}
    steps:
    - name: Assigns inputs passed to the reusable workflow
      id: step1
      run: |
        echo "APP_NAME1=$APP_NAME1" >> $GITHUB_OUTPUT
        echo "APP_NAME2=$APP_NAME2" >> $GITHUB_OUTPUT
        echo "KBC_DEVELOPERPORTAL_VENDOR=$KBC_DEVELOPERPORTAL_VENDOR" >> $GITHUB_OUTPUT
        echo "KBC_DEVELOPERPORTAL_USERNAME=$KBC_DEVELOPERPORTAL_USERNAME" >> $GITHUB_OUTPUT
        echo "KBC_TEST_PROJECT_CONFIGS=$KBC_TEST_PROJECT_CONFIGS" >> $GITHUB_OUTPUT
        echo "DOCKERHUB_USER=$DOCKERHUB_USER" >> $GITHUB_OUTPUT
        echo "PGSQL_HOST=$PGSQL_HOST" >> $GITHUB_OUTPUT
        echo "PGSQL_USER=$PGSQL_USER" >> $GITHUB_OUTPUT
        echo "PGSQL_DATABASE=$PGSQL_DATABASE" >> $GITHUB_OUTPUT
        echo "PGSQL_PORT=$PGSQL_PORT" >> $GITHUB_OUTPUT

  build-java:
    uses: keboola/python-cdc-component/.github/workflows/java.yml@main

  test-python-common:
    uses: keboola/python-cdc-component/.github/workflows/test-python-common.yml@fix/db-common-test-workflow

  build-python:
    name: Build and Push Postgres CDC image
    needs:
      - build-java
      - variables
      - test-python-common
    uses: keboola/python-cdc-component/.github/workflows/build.yml@update-postgre-pipeline
    with:
      APP_ID: ${{ needs.variables.outputs.APP_NAME1 }}
      APP_NAME: ${{ needs.variables.outputs.APP_NAME1 }}
      KBC_DEVELOPERPORTAL_VENDOR: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_VENDOR }}
      KBC_DEVELOPERPORTAL_USERNAME: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_USERNAME }}
      DOCKERHUB_USER: ${{ needs.variables.outputs.DOCKERHUB_USER }}
    secrets: inherit

  build-python-postgres-cdc-duck:
    name: Build and Push Postgres CDC duck image
    needs:
      - build-java
      - variables
    uses: keboola/python-cdc-component/.github/workflows/build.yml@update-postgre-pipeline
    with:
      APP_ID: ${{ needs.variables.outputs.APP_NAME2 }}
      APP_NAME: ${{ needs.variables.outputs.APP_NAME1 }}
      KBC_DEVELOPERPORTAL_VENDOR: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_VENDOR }}
      KBC_DEVELOPERPORTAL_USERNAME: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_USERNAME }}
      DOCKERHUB_USER: ${{ needs.variables.outputs.DOCKERHUB_USER }}
    secrets: inherit

  tests:
    runs-on: ubuntu-latest
    needs:
      - build-python
      - variables
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: java-artifact

      - name: Move JAR Artifact
        run: mv kbcDebeziumEngine-jar-with-dependencies.jar debezium_core/jars/kbcDebeziumEngine-jar-with-dependencies.jar

      - name: Run Tests
        run: |
          cd db_components/ex_postgres_cdc
          docker-compose build tests
          docker-compose run wait
          docker-compose run tests

  tests-kbc:
    needs:
      - build-python
      - variables
    uses: keboola/python-cdc-component/.github/workflows/tests-kbc.yml@main
    with:
      APP_NAME: ${{ needs.variables.outputs.APP_NAME1 }}
      TAG: ${{ needs.build-python.outputs.app_image_tag }}
      KBC_DEVELOPERPORTAL_VENDOR: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_VENDOR }}
      KBC_TEST_PROJECT_CONFIGS: ${{ needs.variables.outputs.KBC_TEST_PROJECT_CONFIGS }}
    secrets: inherit

  deploy-ex-postgres-cdc:
    name: Deploy ex-postgres-cdc
    if: |
       (
         startsWith(github.ref, 'refs/tags/') &&
         (
           (needs.build-python.outputs.is_semantic_tag == 'true') &&
           (
             contains(needs.build-python.outputs.app_image_tag, 'Mysql') ||
             contains(needs.build-python.outputs.app_image_tag, 'mysql') ||
             contains(needs.build-python.outputs.app_image_tag, 'MYSQL') ||
             contains(needs.build-python.outputs.app_image_tag, 'General') ||
             contains(needs.build-python.outputs.app_image_tag, 'general') ||
             contains(needs.build-python.outputs.app_image_tag, 'GENERAL')
           )
         )
       )
    needs:
      - build-python
      - tests
      - tests-kbc
      - variables
    uses: keboola/python-cdc-component/.github/workflows/deploy.yml@update-postgre-pipeline # change to main before deploy!
    with:
      APP_NAME: ${{ needs.variables.outputs.APP_NAME1 }}
      APP_ID: ${{ needs.variables.outputs.APP_NAME1 }}
      KBC_DEVELOPERPORTAL_VENDOR: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_VENDOR }}
      KBC_DEVELOPERPORTAL_USERNAME: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_USERNAME }}
      TAG: ${{ needs.build-python.outputs.app_image_tag }}
      IS_SEMANTIC_TAG: ${{ needs.build-python.outputs.is_semantic_tag }}
    secrets: inherit

  deploy-ex-postgres-cdc-duck:
    name: Deploy ex-postgres-cdc-duck
    if: |
       (
         startsWith(github.ref, 'refs/tags/') &&
         (
           (needs.build-python.outputs.is_semantic_tag == 'true') &&
           (
             contains(needs.build-python.outputs.app_image_tag, 'Mysql') ||
             contains(needs.build-python.outputs.app_image_tag, 'mysql') ||
             contains(needs.build-python.outputs.app_image_tag, 'MYSQL') ||
             contains(needs.build-python.outputs.app_image_tag, 'General') ||
             contains(needs.build-python.outputs.app_image_tag, 'general') ||
             contains(needs.build-python.outputs.app_image_tag, 'GENERAL')
           )
         )
       )
    needs:
      - build-python
      - tests
      - tests-kbc
      - variables
    uses: keboola/python-cdc-component/.github/workflows/deploy.yml@update-postgre-pipeline # change to main before deploy!
    with:
      APP_NAME: ${{ needs.variables.outputs.APP_NAME1 }}
      APP_ID: ${{ needs.variables.outputs.APP_NAME2 }}
      KBC_DEVELOPERPORTAL_VENDOR: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_VENDOR }}
      KBC_DEVELOPERPORTAL_USERNAME: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_USERNAME }}
      TAG: ${{ needs.build-python.outputs.app_image_tag }}
      IS_SEMANTIC_TAG: ${{ needs.build-python.outputs.is_semantic_tag }}
    secrets: inherit