name: Oracle CDC Build & Deploy
on: [ push ]
concurrency: ci-${{ github.ref }} # to avoid tag collisions in the ECR
env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  APP_NAME: "ex-oracle-cdc"
  KBC_DEVELOPERPORTAL_VENDOR: "kds-team"
  KBC_DEVELOPERPORTAL_USERNAME: "kds-team+github"

  # Test KBC project: https://connection.keboola.com/admin/projects/9382
  KBC_TEST_PROJECT_CONFIGS: "" # space separated list of config ids

  DOCKERHUB_USER: "keboolabot"

jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      APP_NAME: ${{ steps.step1.outputs.APP_NAME }}
      KBC_DEVELOPERPORTAL_VENDOR: ${{ steps.step1.outputs.KBC_DEVELOPERPORTAL_VENDOR }}
      KBC_DEVELOPERPORTAL_USERNAME: ${{ steps.step1.outputs.KBC_DEVELOPERPORTAL_USERNAME }}
      KBC_TEST_PROJECT_CONFIGS: ${{ steps.step1.outputs.KBC_TEST_PROJECT_CONFIGS }}
      DOCKERHUB_USER: ${{ steps.step1.outputs.DOCKERHUB_USER }}
    steps:
      - name: Print inputs passed to the reusable workflow
        id: step1
        run: |
          echo "APP_NAME=$APP_NAME" >> $GITHUB_OUTPUT
          echo "KBC_DEVELOPERPORTAL_VENDOR=$KBC_DEVELOPERPORTAL_VENDOR" >> $GITHUB_OUTPUT
          echo "KBC_DEVELOPERPORTAL_USERNAME=$KBC_DEVELOPERPORTAL_USERNAME" >> $GITHUB_OUTPUT
          echo "KBC_TEST_PROJECT_CONFIGS=$KBC_TEST_PROJECT_CONFIGS" >> $GITHUB_OUTPUT
          echo "DOCKERHUB_USER=$DOCKERHUB_USER" >> $GITHUB_OUTPUT

  build-java:
    uses: keboola/python-cdc-component/.github/workflows/java.yml@add-oracle-cdc

  build-python:
    name: Build and Push Oracle CDC image
    needs:
      - build-java
      - variables
    uses: keboola/python-cdc-component/.github/workflows/build.yml@add-oracle-cdc
    with:
      APP_ID: ${{ needs.variables.outputs.APP_NAME }}
      APP_NAME: ${{ needs.variables.outputs.APP_NAME }}
      KBC_DEVELOPERPORTAL_VENDOR: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_VENDOR }}
      KBC_DEVELOPERPORTAL_USERNAME: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_USERNAME }}
      DOCKERHUB_USER: ${{ needs.variables.outputs.DOCKERHUB_USER }}
    secrets: inherit

  tests:
    needs:
      - build-python
      - variables
    uses: keboola/python-cdc-component/.github/workflows/tests.yml@add-oracle-cdc
    with:
      APP_NAME: ${{ needs.variables.outputs.APP_NAME }}
      KBC_DEVELOPERPORTAL_VENDOR: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_VENDOR }}
      KBC_DEVELOPERPORTAL_USERNAME: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_USERNAME }}
      TAG: ${{ needs.build-python.outputs.app_image_tag }}
    secrets: inherit

  tests-kbc:
    needs:
      - build-python
      - variables
    uses: keboola/python-cdc-component/.github/workflows/tests-kbc.yml@add-oracle-cdc
    with:
      APP_NAME: ${{ needs.variables.outputs.APP_NAME }}
      TAG: ${{ needs.build-python.outputs.app_image_tag }}
      KBC_DEVELOPERPORTAL_VENDOR: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_VENDOR }}
      KBC_TEST_PROJECT_CONFIGS: ${{ needs.variables.outputs.KBC_TEST_PROJECT_CONFIGS }}
    secrets: inherit

  deploy-ex-oracle-cdc:
    # if: |
    #   (
    #     startsWith(github.ref, 'refs/tags/') &&
    #     (
    #       (needs.build-python.outputs.is_semantic_tag == 'true') &&
    #       (
    #         startsWith(needs.build-python.outputs.app_image_tag, 'Oracle') ||
    #         startsWith(needs.build-python.outputs.app_image_tag, 'oracle') ||
    #         startsWith(needs.build-python.outputs.app_image_tag, 'ORACLE') ||
    #         startsWith(needs.build-python.outputs.app_image_tag, 'General') ||
    #         startsWith(needs.build-python.outputs.app_image_tag, 'general') ||
    #         startsWith(needs.build-python.outputs.app_image_tag, 'GENERAL')
    #       )
    #     )
    #   )
    needs:
      - build-python
      - tests
      - tests-kbc
      - variables
    uses: keboola/python-cdc-component/.github/workflows/deploy.yml@add-oracle-cdc
    with:
      APP_NAME: ${{ needs.variables.outputs.APP_NAME }}
      APP_ID: ${{ needs.variables.outputs.APP_NAME }}
      KBC_DEVELOPERPORTAL_VENDOR: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_VENDOR }}
      KBC_DEVELOPERPORTAL_USERNAME: ${{ needs.variables.outputs.KBC_DEVELOPERPORTAL_USERNAME }}
      TAG: "0.0.3" # ${{ needs.build-python.outputs.app_image_tag }}
      IS_SEMANTIC_TAG: ${{ needs.build-python.outputs.is_semantic_tag }}
    secrets: inherit
