name: Github Actions
on: [ push ]
concurrency: ci-${{ github.ref }} # to avoid tag collisions in the ECR
env:
  KBC_COMPONENTS: "app-python-cdc-component-test"
  APP_IMAGE: "keboola-component"
  KBC_DEVELOPERPORTAL_URL: "https://apps-api.keboola.com"
  KBC_DEVELOPERPORTAL_USERNAME: "kds-team+github"
  KBC_DEVELOPERPORTAL_VENDOR: "kds-team"
  KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}

  # DockerHub login
  DOCKERHUB_USER: "keboolabot"
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # Test KBC project
  KBC_STORAGE_TOKEN: ${{ secrets.KBC_STORAGE_TOKEN }}
  KBC_TEST_PROJECT_URL: "https://connection.keboola.com/admin/projects/9382" # INFO ONLY
  KBC_TEST_PROJECT_CONFIGS: "1083217486" # space separated list

jobs:
  build-java:
    uses: keboola/python-cdc-component/.github/workflows/java.yml@main

  build-python:
    needs: build-java
    uses: keboola/python-cdc-component/.github/workflows/build.yml@main
    with:
      APP_NAME: "app-python-cdc-component-test"
      APP_IMAGE: "keboola-component"
      VENDOR: "kds-team"
      USERNAME: "kds-team+github"
      DOCKERHUB_USER: "keboolabot"
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    secrets: inherit

  tests:
    needs: build-python
    uses: keboola/python-cdc-component/.github/workflows/tests.yml@main
    with:
      VENDOR: "kds-team"
      APP_NAME: "app-python-cdc-component-test"
      USERNAME: "kds-team+github"
      TAG: ${{ needs.build-python.outputs.app_image_tag }}
      APP_IMAGE: "app-python-cdc-component-test"
    secrets: inherit

  tests-kbc:
    needs: build-python
    uses: keboola/python-cdc-component/.github/workflows/tests-kbc.yml@main
    with:
      APP_NAME: "app-python-cdc-component-test"
      TAG: ${{ needs.build-python.outputs.app_image_tag }}
    secrets: inherit

  deploy:
    needs:
      - build-python
      - tests
      - tests-kbc
    uses: keboola/python-cdc-component/.github/workflows/deploy.yml@main
    with:
      VENDOR: "kds-team"
      APP_ID: "app-python-cdc-component-test"
      USERNAME: "kds-team+github"
      TAG: ${{ needs.build-python.outputs.app_image_tag }}
      IS_SEMANTIC_TAG: ${{ needs.build-python.outputs.is_semantic_tag }}
    secrets: inherit