name: Github Actions
on: [ push ]
concurrency: ci-${{ github.ref }} # to avoid tag collisions in the ECR
env:
  KBC_COMPONENTS: "app-python-cdc-component-test"
  APP_IMAGE: "keboola-component"
  KBC_DEVELOPERPORTAL_URL: "https://apps-api.keboola.com"
  KBC_DEVELOPERPORTAL_USERNAME: "kds-team+github"
  KBC_DEVELOPERPORTAL_VENDOR: "kds-team"
  KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}

  # DockerHub login
  DOCKERHUB_USER: "keboolabot"
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # Test KBC project
  KBC_STORAGE_TOKEN: ${{ secrets.KBC_STORAGE_TOKEN }}
  KBC_TEST_PROJECT_URL: "https://connection.keboola.com/admin/projects/9382" # INFO ONLY
  KBC_TEST_PROJECT_CONFIGS: "1083217486" # space separated list

jobs:
  build-java:
    name: build-java
    uses: keboola/python-cdc-component/.github/workflows/java.yml@pipeline-polish

  build-python:
    needs: build-java
    uses: keboola/python-cdc-component/.github/workflows/build.yml@pipeline-polish
    with:
      APP_NAME: "app-python-cdc-component-test"

  tests:
    needs: build-python
    uses: keboola/python-cdc-component/.github/workflows/tests.yml@pipeline-polish
    with:
      APP_NAME: "app-python-cdc-component-test"
      TAG: ${{ needs.build-python.outputs.app_image_tag }}

  tests-kbc:
    needs: build-python
    uses: keboola/python-cdc-component/.github/workflows/tests-kbc.yml@pipeline-polish
    with:
      APP_NAME: "app-python-cdc-component-test"
      TAG: ${{ needs.build-python.outputs.app_image_tag }}

  deploy:
    needs:
      - build-python
      - tests
      - tests-kbc
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && needs.build-python.outputs.is_semantic_tag == 'true'
    steps:
      - name: Set tag in the Developer Portal
        uses: keboola/action-set-tag-developer-portal@master
        with:
          vendor: ${{ env.KBC_DEVELOPERPORTAL_VENDOR }}
          app_id: ${{ env.KBC_DEVELOPERPORTAL_APP }}
          username: ${{ env.KBC_DEVELOPERPORTAL_USERNAME }}
          password: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ needs.build-python.outputs.app_image_tag }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set developer portal properties
        run: |
            chmod +x scripts/update_dev_portal_properties.sh
            scripts/update_dev_portal_properties.sh
