on:
  workflow_call:
    inputs:
      KBC_DEVELOPERPORTAL_VENDOR:
        required: true
        type: string
      APP_NAME:
        required: true
        type: string
      KBC_DEVELOPERPORTAL_USERNAME:
        required: true
        type: string
      TAG:
        required: false
        type: string
      PGSQL_HOST:
        required: false
        type: string
      PGSQL_USER:
        required: false
        type: string
      PGSQL_PASSWORD:
        required: false
        type: string
      PGSQL_DATABASE:
        required: false
        type: string
      PGSQL_PORT:
        required: false
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "PSQL_HOST=${{ inputs.PSQL_HOST }}" >> $GITHUB_ENV
          echo "PSQL_USER=${{ inputs.PSQL_USER }}" >> $GITHUB_ENV
          echo "PSQL_PASSWORD=${{ inputs.PSQL_PASSWORD }}" >> $GITHUB_ENV
          echo "PSQL_DATABASE=${{ inputs.PSQL_DATABASE }}" >> $GITHUB_ENV
          echo "PSQL_PORT=${{ inputs.PSQL_PORT }}" >> $GITHUB_ENV

      - name: Pull image from ECR
        uses: keboola/action-pull-from-ecr@master
        with:
          vendor: ${{ inputs.KBC_DEVELOPERPORTAL_VENDOR }}
          app_id: ${{ inputs.KBC_DEVELOPERPORTAL_VENDOR }}.${{ inputs.APP_NAME }}
          username: ${{ inputs.KBC_DEVELOPERPORTAL_USERNAME }}
          password: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ inputs.TAG }}
          target_image: ${{ inputs.APP_NAME}}
          tag_as_latest: true

      - name: Set APP_PATH variable
        run: echo "APP_PATH=$(echo ${{ inputs.APP_NAME }} | tr '-' '_')" >> $GITHUB_ENV

      - name: Run tests
        run: |
          docker run ${{ inputs.APP_NAME }} flake8 . --config=/code/db_components/${{ env.APP_PATH }}/flake8.cfg
          echo "Running unit-tests..."
          docker run ${{ inputs.APP_NAME }} python -m unittest discover
