on:
  workflow_call:
jobs:
  unit-tests:
    env:
      KBC_TOKEN: ${{ secrets.KBC_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set APP_PATH variable
        run: echo "KBC_TOKEN=${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r db_components/requirements-common.txt

      - name: Run Tests
        run: |
          python -m unittest discover db_components/tests 
